spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
  config:
    import: optional:configserver:http://localhost:8085
  application:
    name: TODO-SERVICE
  data:
    mongodb:
      port: '27017'
      auto-index-creation: 'true'
      database: todo_db
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: 'true'
  endpoint:
    metrics:
      enabled: 'true'
    prometheus:
      enabled: 'true'
  server:
    port: '9091'
eureka:
  instance:
    leaseExpirationDurationInSeconds: '2'
    leaseRenewalIntervalInSeconds: '1'
    appname: todo-service
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /todolist/
  port: '8082'
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
